### ISSUE TITLE
Running outside of CI gives unhelpful error message

### ISSUE THREAD

**Issue by Logiraptor** [sagotch/ocveralls#21]
I just tried running ocveralls locally to make sure it was working before pushing to github, and I got a Not_found error with no helpful description. Luckily, the source is rather clear, so I tracked it down to [this](https://github.com/sagotch/ocveralls/blob/master/src/ocverallsCI.ml#L39) call to `List.find`. It would be helpful if the tool could instead print a helpful error which says something about running only in CI with the relevant env vars defined.

**Comment by sagotch** [comment]
You are right. Note that you can use the `--repo_token` option locally https://github.com/sagotch/ocveralls/blob/master/src/ocveralls.ml#L84

**Comment by sagotch** [comment]
2403650e85ebefe6e0f6ab624b914cf63bf98ad7
