### ISSUE TITLE
More detailed error messages

### ISSUE THREAD

**Issue by yallop** [sagotch/ocveralls#9]
A recent Travis build of ctypes [failed](https://travis-ci.org/ocamllabs/ocaml-ctypes/jobs/72650982#L3586) with an ocveralls assertion error:

<code>
Fatal error: exception File ["src/ocveralls.ml", line 135, characters 14-20](https://github.com/sagotch/ocveralls/blob/c80388b8d3f699a2e95a532bce98439966c441f3/src/ocveralls.ml#L135): Assertion failed
</code>

It'd be useful for the error message to include more information about what went wrong.

**Comment by sagotch** [comment]
Fixed in 0.3.1 version (which should be available in opam soon).
Thanks for reporting, I hope this is what you had in mind!

**Comment by yallop** [comment]
Thanks!  This certainly looks like an improvement.
